controller:
  componentName: "jenkins-controller"
  image: "jenkins/jenkins"
  tag: "2.375.1-jdk17"
  imagePullPolicy: "Always"
  adminUser: "admin"
  adminPassword: "admin"

  # List of plugins to be install during Jenkins controller start
  installPlugins:
    - kubernetes:3743.v1fa_4c724c3b_7
    - kubernetes-cli:1.10.3
    - workflow-aggregator:590.v6a_d052e5a_a_b_5
    - docker-workflow:563.vd5d2e5c4007f
    - job-dsl:1.81
    - git:4.14.3
    - configuration-as-code:1569.vb_72405b_80249
    - command-launcher:90.v669d7ccb_7c31
    - pipeline-utility-steps:2.14.0

  JCasC:
    defaultConfig: true
    configScripts: 
      welcome-message: |
        jenkins:
          systemMessage: Welcome my dynamic pipeline demo.
      configuration: |
        jobs:
          - script: >
              pipelineJob('Simple-App') {
                definition {
                  cps {
                    script("""\
                      @Library (['core']) _
                      properties([
                          parameters(
                              [ string(name: 'REPO_BRANCH', defaultValue: 'main', description: 'git repository branch') ]
                          )
                      ])
                      params.each { k, v -> env[k] = v }

                      env.REPO_URL = "https://github.com/febarbosa182/pipeline-simple-app.git"
                      env.TECH_TYPE= "angular"
                      env.KUBE_NAMESPACE = "default"
                      env.HELM_RELEASE_NAME = "pipeline-simple-app"
                      env.HELM_CHART_NAME = "pipeline-simple-app"
                      env.DOCKER_IMAGE = "febarbosa182/pipeline-simple-app"
                      env.CI_IMAGE = "node:lts"
                      
                      coreLibrary{}
                    """.stripIndent())
                  }
                }
              }
        unclassified:
          globalLibraries:
            libraries:
              - name: "core"
                defaultVersion: "main"
                retriever:
                  modernSCM:
                    scm:
                      git:
                        remote: "https://github.com/febarbosa182/pipeline-core.git"
    

agent:
  enabled: true
  image: "jenkins/inbound-agent"
  tag: "4.11.2-4-jdk11"
